kind = "mobile"
previewPath = "/"
title = "Diyoun - Debt Tracker"
version = "1.0.0"
id = "artifacts/debts"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19445

[services.development]
run = "pnpm --filter @workspace/debts run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/debts", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/debts", "run", "serve" ]

[services.env]
PORT = "19445"
BASE_PATH = "/"
